### ISSUE TITLE
New languages

### ISSUE THREAD

**Issue by RafaelMD** [Microsoft/ConversationLearner-SDK#253]
First of all, very cool project :)

How hard would be to add new languages? How could I help with that? Can you give me some directions? 

Thanks

**Comment by jasondwilliams** [comment]
Hi @RafaelMD, @BelvedereHenrique - Adding more languages is definitely on the roadmap, but I don't have a date to share.  The bulk of the work would be on the cloud service, not SDK/UI/client.  Would you consider making an entries on our [User Voice page](https://cognitive.uservoice.com/forums/912199-project-conversation-learner) for languages you think are important?  I'd suggest one entry per language, so people can vote up languages they  think are most important.

**Comment by BelvedereHenrique** [comment]
Done.

Since the ideia is to people vote on the more important ones, I went ahead and registered every language luis.ai supports.

Thank you.

**Comment by BelvedereHenrique** [comment]
@jasondwilliams Is this cloud service open source?

**Comment by LarsLiden** [comment]
Awesome.  Thanks!

**Comment by LarsLiden** [comment]
The service itself is not open source.

**Comment by mattmazzola** [comment]
Going to close this since the request for languages is now on [UserVoice](https://cognitive.uservoice.com/forums/912199-project-conversation-learner)

Adding more language support is something that requires changes to the back-end service and we would make an announcement when any of them are added in the future.
