### ISSUE TITLE
API results not shown in training (Missing ConversationReference)

### ISSUE THREAD

**Issue by michaelneu** [Microsoft/ConversationLearner-SDK#335]
`@conversationlearner/sdk` version: 0.275.7

When scoring API actions in training, the result of the action won't be sent back to the training dialog, as there's no conversation reference found. Furthermore, `this.adapter` appears to be `null`, thus no message can be sent back to the training dialog:

https://github.com/Microsoft/ConversationLearner-SDK/blob/e946d27171a69964dc0bd2b29e21106d7d23ca70/src/CLRunner.ts#L834-L845

As both checks will fail, the API actions won't be called after being scored.

##  Steps to reproduce

- add API actions
- start training
- score an API action
- the action's result won't be shown in the training dialog

## Workaround / Hack

It appears, undoing a new, temporary action (e.g. entering `foo` and undoing it) will invoke the actions and make the UI render the whole history. This seems to be due to conversation learner re-executing the whole history.

This execution might also raise some more issues when interacting with realtime APIs, whose data might change while undoing an action, as the results, the conversation learner relies on, may change.

**Comment by michaelneu** [comment]
Any updates on this? From what I saw, there might not be an easy fix, as there's no conversation while training (i.e. fix required on both front- and backend).

In case somebody came here because they're experiencing the same (`@next` doesn't work either for me right now), you can edit `node_modules/@conversationlearner/sdk/lib/CLRunner.js` locally to at least continue training your models.

**Important:  This will have side effects, some obvious ones, some not so obvious, so don't do this in production! This is just for training!**

```js
            // I HAVE READ THE ABOVE "IMPORTANT" MESSAGE AND AM AWARE
            // THAT THIS WILL PROBABLY BREAK SOMETHING

            // comment out the throw statement on line CLRunner.js:538 (in @next)
            // if (!conversationReference.conversation) {
            //     throw new Error(`ConversationReference contains no conversation`);
            // }
```

```js
    // I HAVE READ THE ABOVE "IMPORTANT" MESSAGE AND AM AWARE
    // THAT THIS WILL PROBABLY BREAK SOMETHING

    // replace SendIntent on line CLRunner.js:613 (in @next) with the following method
    SendIntent(intent, inTeach = false) {
        return tslib_1.__awaiter(this, void 0, void 0, function* () {
            let conversationReference = yield intent.memory.BotState.GetConversationReverence();
            if (!conversationReference) {
                CLDebug_1.CLDebug.Error('Missing ConversationReference');
                // we don't have a conversationReference, so we need to come up with one.
                // this will most definitely have side effects (one is an unhandled promise
                // rejection when using an END_SESSION action, many more could occur)
                conversationReference = {
                    conversation: {},
                };

                // don't exit here, as we want to reach the rendering
                // return;
            }
            if (!this.adapter) {
                CLDebug_1.CLDebug.Error('Missing Adapter');
                // don't exit here, as we want to reach the rendering
                // return;
            }
            const actionResult = yield this.RenderTemplateAsync(conversationReference, intent, inTeach);

            // prevent null dereference and check if there's an adapter
            if (this.adapter && actionResult.response != null) {
                yield this.adapter.continueConversation(conversationReference, (context) => tslib_1.__awaiter(this, void 0, void 0, function* () {
                    // Need to repeat null check as compiler is catching one above for explicit null
                    if (actionResult.response != null) {
                        yield context.sendActivity(actionResult.response);
                    }
                }));
            }
            return actionResult;
        });
    }
```

Again, this is a **temporary** fix, use with caution.

**Comment by msft-shahins** [comment]
I tried to repro this on sdk version `0.275.7` with the latest [sdk sample code](https://github.com/Microsoft/ConversationLearner-Samples) by following the repro steps provided but didn't have any success with it (everything worked as expected for me). It would be great to have more details about the condition that you see this bug. 

`conversation reference` is necessary for sdk to send back response activities to web chat when in a teach session (UI) since the code path for teach API is different than the regular bot's code path for message processing. In current implementation, I can see that there might be some timing issues in some cases that cause `conversation reference` not to be set correctly. We are trying to see what is the best design change that we can make to the SDK and UI to make conversation reference more reliable. But in the mean time, it would be good to have a better understanding about the cases that you are seeing the issue. 

In your comments you mentioned the point below which is a valid point:
> This execution might also raise some more issues when interacting with realtime APIs, whose data might change while undoing an action, as the results, the conversation learner relies on, may change.

To reduce impact of changes in the result of API, the next release of SDK separates business logic from rendering path in API callbacks (They will be explicitly defined by developer) https://github.com/Microsoft/ConversationLearner-SDK/commit/561a5a0958df2fabce93ee51150ee54469adddac. As a result replay of history only calls into rendering logic and skip the business logic. Because of this change current @next version of SDK has breaking changes that are not backward compatible with current signature of API callbacks.

**Comment by michaelneu** [comment]
Sorry, that one is on me.

I went through the samples repo once more and found out `offline-directline` is now (since 07/06) started using the corresponding module, instead of via the sdk - totally missed that. There used to be environment variables for this, but I just didn't notice the "new" `dol.ts`...

>As a result replay of history only calls into rendering logic and skip the business logic.

I actually saw this while trying to debug why my messages wouldn't appear in `@next`, that's a good improvement!

Thanks for your help, closing this as it was a user-error, not related to the sdk.
